// src/frontend/components/landing/NewsComponent.svelte
<style>
  #newsContainer.hideNewsSection {
    top: 100%;
  }
  #newsContainer {
    top: 0px;
  }
</style>

<script lang="ts">
  type News = {
    author: string;
    date: Date;
    title: string;
    comments: string[];
    content: string;
    url: string;
  };

  export let showNews = false;
  let hasError = false;
  let news: News[] = [];
  let loading = true;
  let currentNewIndex = -1;
  $: displayedValue = news[currentNewIndex];

  setTimeout(() => {
    hasError = true;
    loading = false;
  }, 2000);

  function handleReloading() {
    hasError = false;
    loading = true;
    setTimeout(() => {
      const newToPush = {
        author: "Shadowner",
        comments: ["hello", "world"],
        content:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore sint laboriosam, autem, ad, hic doloremque eligendi dolorum facere totam reiciendis maxime quia porro? Quae nemo vel modi neque nisi? Illum!",
        date: new Date(),
        title: "Svelte is coming to the Party",
        url: "http://localhost/",
      };

      news.push(newToPush, newToPush, newToPush, newToPush, newToPush, newToPush, newToPush, newToPush, newToPush);
      currentNewIndex = 0;
      loading = false;
    }, 1000);
  }

  function handleNext() {
    if (currentNewIndex < news.length - 1) currentNewIndex++;
  }

  function handlePrevious() {
    if (currentNewIndex > 0) currentNewIndex--;
  }
</script>

<div id="newsContainer" class:hideNewsSection="{!showNews}">
  {#if !loading && news.length > 0 && displayedValue}
    <div id="newsContent">
      <div id="newsStatusContainer">
        <div id="newsStatusContent">
          <div id="newsTitleContainer">
            <a id="newsArticleTitle" href="{displayedValue.url}">{displayedValue.title}</a>
          </div>
          <div id="newsMetaContainer">
            <div id="newsArticleDateWrapper">
              <span id="newsArticleDate">{displayedValue.date.toLocaleDateString()}</span>
            </div>
            <div id="newsArticleAuthorWrapper">
              <span id="newsArticleAuthor">by {displayedValue.author}</span>
            </div>
            <a href="{displayedValue.url}/comments" id="newsArticleComments">{displayedValue.comments?.length}</a>
          </div>
        </div>
        <div id="newsNavigationContainer">
          <button id="newsNavigateLeft" on:click="{handlePrevious}">
            <svg id="newsNavigationLeftSVG" viewBox="0 0 24.87 13.97">
              <defs>
                <style>
                  .arrowLine {
                    fill: none;
                    stroke: #fff;
                    stroke-width: 2px;
                    transition: 0.25s ease;
                  }
                </style>
              </defs>
              <polyline class="arrowLine" points="0.71 13.26 12.56 1.41 24.16 13.02"></polyline>
            </svg>
          </button>
          <span id="newsNavigationStatus">{currentNewIndex + 1} of {news.length}</span>
          <button id="newsNavigateRight" on:click="{handleNext}">
            <svg id="newsNavigationRightSVG" viewBox="0 0 24.87 13.97">
              <defs>
                <style>
                  .arrowLine {
                    fill: none;
                    stroke: #fff;
                    stroke-width: 2px;
                    transition: 0.25s ease;
                  }
                </style>
              </defs>
              <polyline class="arrowLine" points="0.71 13.26 12.56 1.41 24.16 13.02"></polyline>
            </svg>
          </button>
        </div>
      </div>
      <div id="newsArticleContainer">
        <div id="newsArticleContent">
          <div id="newsArticleContentScrollable">
            {displayedValue.content}
          </div>
        </div>
      </div>
    </div>
  {/if}
  <div id="newsErrorContainer">
    {#if loading && !hasError}
      <div id="newsErrorLoading">
        <span id="nELoadSpan" class="newsErrorContent">Checking for News..</span>
      </div>
    {:else if !loading && hasError}
      <div id="newsErrorFailed">
        <span id="nEFailedSpan" class="newsErrorContent">Failed to Load News</span>
        <button id="newsErrorRetry" on:click="{handleReloading}">Try Again</button>
      </div>
    {:else if news.length === 0}
      <div id="newsErrorNone">
        <span id="nENoneSpan" class="newsErrorContent">No News</span>
      </div>
    {/if}
  </div>
</div>

// src/renderer/components/news/News.tsx
import * as React from 'react'

import './News.css'

export default class News extends React.Component {


    render(): JSX.Element {

        return (
            <>
                <div id="newsContainer">
                    <div id="newsContent" {...{article: '-1'}} style={{display: 'none'}}>
                        <div id="newsStatusContainer">
                            <div id="newsStatusContent">
                                <div id="newsTitleContainer">
                                    <a id="newsArticleTitle" href="#">Lorem Ipsum</a>
                                </div>
                                <div id="newsMetaContainer">
                                    <div id="newsArticleDateWrapper">
                                        <span id="newsArticleDate">Mar 15, 44 BC, 9:14 AM</span>
                                    </div>
                                    <div id="newsArticleAuthorWrapper">
                                        <span id="newsArticleAuthor">by Cicero</span>
                                    </div>
                                    <a href="#" id="newsArticleComments">0 Comments</a>
                                </div>
                            </div>
                            <div id="newsNavigationContainer">
                                <button id="newsNavigateLeft">
                                    <svg id="newsNavigationLeftSVG" viewBox="0 0 24.87 13.97">
                                        <polyline style={{transition: '0.25s ease'}} fill="none" stroke="#FFF" strokeWidth="2px" points="0.71 13.26 12.56 1.41 24.16 13.02"/>
                                    </svg>
                                </button>
                                <span id="newsNavigationStatus">1 of 1</span>
                                <button id="newsNavigateRight">
                                    <svg id="newsNavigationRightSVG" viewBox="0 0 24.87 13.97">
                                        <polyline style={{transition: '0.25s ease'}} fill="none" stroke="#FFF" strokeWidth="2px" points="0.71 13.26 12.56 1.41 24.16 13.02"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                        <div id="newsArticleContainer">
                            <div id="newsArticleContent">
                                <div id="newsArticleContentScrollable">
                                    {/*  Article Content */}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="newsErrorContainer">
                        <div id="newsErrorLoading">
                            <span id="nELoadSpan" className="newsErrorContent">Checking for News..</span>
                        </div>
                        <div id="newsErrorFailed" style={{display: 'none'}}>
                            <span id="nEFailedSpan" className="newsErrorContent">Failed to Load News</span>
                            <button id="newsErrorRetry">Try Again</button>
                        </div>
                        <div id="newsErrorNone" style={{display: 'none'}}>
                            <span id="nENoneSpan" className="newsErrorContent">No News</span>
                        </div>
                    </div>
                </div>

            </>
        )

    }

}
