// src/renderer/components/welcome/Welcome.tsx
import * as React from 'react';
import './Welcome.css';

const Welcome = () => (
    <div id="welcomeContainer">
        <div id="welcomeContent">
            <img id="welcomeImageSeal" src="../images/SealCircle.png"/>
            <span id="welcomeHeader">WELCOME TO HELIOS LAUNCHER</span>
            <span id="welcomeDescription">Our mission is to provide modded servers with a simple and reliable client. When a server needs more than vanilla minecraft offers, they turn to modding platforms to fill in the gaps. Managing and deploying client updates can be difficult and time consuming. Helios Launcher provides a platform to handle all of this for you through a customized, simple, and elegant client. It shouldn't be hard to play modded minecraft. It's shouldn't be hard to set up Java. With Helios, it isn't. Let's get going.</span>
            <br />
            <span id="welcomeDescCTA">You are just a few clicks away from the game.</span>
            <button id="welcomeButton">
                <div id="welcomeButtonContent">
                    CONTINUE
                    <svg id="welcomeSVG" viewBox="0 0 24.87 13.97">
                        <polyline style={{fill:'none', stroke:'#FFF', strokeWidth:'2px', transition: '0.25s ease'}} strokeWidth="2px"  points="0.71 13.26 12.56 1.41 24.16 13.02"/>
                    </svg>
                </div>
            </button>
        </div>
    </div>
);

export default Welcome;

// src/frontend/views/Welcome.svelte
<style>
</style>

<script lang="ts">
  import { fade } from "svelte/transition";
  import { currentView } from "../store/AppStore.js";
  import { PossibleViewState } from "../types/PossibleAppState.js";
</script>

<div id="welcomeContainer" out:fade>
  <div id="welcomeContent">
    <img id="welcomeImageSeal" src="assets/images/SealCircle.png" alt="Bienvenue" />
    <span id="welcomeHeader">WELCOME TO WESTEROSCRAFT</span>
    <span id="welcomeDescription"
      >Our mission is to recreate the universe imagined by author George RR Martin in his fantasy series, A Song of Ice
      and Fire. Through the collaborative effort of thousands of community members, we have sought to create Westeros as
      accurately and precisely as possible within Minecraft. The world we are creating is yours to explore. Journey from
      Dorne to Castle Black, and if you aren’t afraid, beyond the Wall itself, but best not delay. As the words of House
      Stark ominously warn: Winter is Coming.</span
    >
    <br />
    <span id="welcomeDescCTA">You are just a few clicks away from Westeros.</span>
    <button id="welcomeButton" on:click="{(e) => currentView.set(PossibleViewState.LoginOptions)}">
      <div id="welcomeButtonContent">
        CONTINUE
        <svg id="welcomeSVG" viewBox="0 0 24.87 13.97">
          <defs>
            <style>
              .arrowLine {
                fill: none;
                stroke: #fff;
                stroke-width: 2px;
                transition: 0.25s ease;
              }
            </style>
          </defs>
          <polyline class="arrowLine" points="0.71 13.26 12.56 1.41 24.16 13.02"></polyline>
        </svg>
      </div>
    </button>
  </div>
</div>
