// src/frontend/views/Login.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import { currentView } from "../store/AppStore";
  import { PossibleViewState } from "../types/PossibleAppState";

  let username = "";
  let password = "";
  let rememberMe = false;

  let isSigningIn = false;

  async function login() {
    isSigningIn = true;
    setTimeout(() => {
      isSigningIn = false;
      currentView.set(PossibleViewState.Landing);
    }, 1000);
  }
</script>

<div id="loginContainer" in:fade="{{ delay: 500 }}" out:fade>
  <div id="loginCancelContainer">
    <button
      id="loginCancelButton"
      disabled="{isSigningIn}"
      on:click="{(e) => currentView.set(PossibleViewState.LoginOptions)}"
    >
      <div id="loginCancelIcon">X</div>
      <span id="loginCancelText">Cancel</span>
    </button>
  </div>
  <div id="loginContent">
    <form id="loginForm">
      <img id="loginImageSeal" src="assets/images/SealCircle.png" alt="seal" />
      <span id="loginSubheader">MINECRAFT LOGIN</span>
      <div class="loginFieldContainer">
        <svg id="profileSVG" class="loginSVG" viewBox="40 37 65.36 61.43">
          <g>
            <path
              d="M86.77,58.12A13.79,13.79,0,1,0,73,71.91,13.79,13.79,0,0,0,86.77,58.12M97,103.67a3.41,3.41,0,0,0,3.39-3.84,27.57,27.57,0,0,0-54.61,0,3.41,3.41,0,0,0,3.39,3.84Z"
            ></path>
          </g>
        </svg>
        <span class="loginErrorSpan" id="loginEmailError">* Invalid Value</span>
        <input
          disabled="{isSigningIn}"
          bind:value="{username}"
          id="loginUsername"
          class="loginField"
          type="text"
          placeholder="EMAIL OR USERNAME"
        />
      </div>
      <div class="loginFieldContainer">
        <svg id="lockSVG" class="loginSVG" viewBox="40 32 60.36 70.43">
          <g>
            <path
              d="M86.16,54a16.38,16.38,0,1,0-32,0H44V102.7H96V54Zm-25.9-3.39a9.89,9.89,0,1,1,19.77,0A9.78,9.78,0,0,1,79.39,54H60.89A9.78,9.78,0,0,1,60.26,50.59ZM70,96.2a6.5,6.5,0,0,1-6.5-6.5,6.39,6.39,0,0,1,3.1-5.4V67h6.5V84.11a6.42,6.42,0,0,1,3.39,5.6A6.5,6.5,0,0,1,70,96.2Z"
            ></path>
          </g>
        </svg>
        <span class="loginErrorSpan" id="loginPasswordError">* Required</span>
        <input
          bind:value="{password}"
          disabled="{isSigningIn}"
          id="loginPassword"
          class="loginField"
          type="password"
          placeholder="PASSWORD"
        />
      </div>
      <div id="loginOptions">
        <span class="loginSpanDim">
          <a href="https://minecraft.net/password/forgot/">forgot password?</a>
        </span>
        <label id="checkmarkContainer">
          <input bind:value="{rememberMe}" disabled="{isSigningIn}" id="loginRememberOption" type="checkbox" checked />
          <span id="loginRememberText" class="loginSpanDim">remember me?</span>
          <span class="loginCheckmark"></span>
        </label>
      </div>
      <button
        id="loginButton"
        class:loading="{isSigningIn}"
        disabled="{username == '' || password == ''}"
        on:click|preventDefault="{login}"
      >
        <div id="loginButtonContent">
          LOGIN
          <svg id="loginSVG" viewBox="0 0 24.87 13.97">
            <defs>
              <style>
                .arrowLine {
                  fill: none;
                  stroke: #fff;
                  stroke-width: 2px;
                  transition: 0.25s ease;
                }
              </style>
            </defs>
            <polyline class="arrowLine" points="0.71 13.26 12.56 1.41 24.16 13.02"></polyline>
          </svg>

          <div class="circle-loader">
            <div class="checkmark draw"></div>
          </div>
          <!--<div class="spinningCircle" id="loginSpinner"></div>-->
        </div>
      </button>
      <div id="loginDisclaimer">
        <span class="loginSpanDim" id="loginRegisterSpan">
          <a href="https://minecraft.net/store/minecraft-java-edition/">Need an Account?</a>
        </span>
        <p class="loginDisclaimerText">Your password is sent directly to mojang and never stored.</p>
        <p class="loginDisclaimerText">Helios Launcher is not affiliated with Mojang AB.</p>
      </div>
    </form>
  </div>
</div>

// src/renderer/components/login/Login.tsx
import * as React from 'react'
import LoginField from './login-field/LoginField'

import './Login.css'

type LoginProperties = {
    cancelable: boolean
}

export default class Login extends React.Component<LoginProperties> {

    getCancelButton(): JSX.Element {
        if(this.props.cancelable) {
            return (
                <>
                    <div id="loginCancelContainer">
                        <button id="loginCancelButton">
                            <div id="loginCancelIcon">X</div>
                            <span id="loginCancelText">Cancel</span>
                        </button>
                    </div>
                </>
            )
        } else {
            return (<></>)
        }
    }

    render() {
        return (
            <>
                <div id="loginContainer">
                    {this.getCancelButton()}
                    <div id="loginContent">
                        <form id="loginForm">
                            <img id="loginImageSeal" src="../images/SealCircle.png"/>
                            <span id="loginSubheader">MINECRAFT LOGIN</span>

                            <LoginField password={false} />
                            <LoginField password={true} />

                            <div id="loginOptions">
                                <span className="loginSpanDim">
                                    <a href="https://my.minecraft.net/en-us/password/forgot/">forgot password?</a>
                                </span>
                                <label id="checkmarkContainer">
                                    <input id="loginRememberOption" type="checkbox" checked></input>
                                    <span id="loginRememberText" className="loginSpanDim">remember me?</span>
                                    <span className="loginCheckmark"></span>
                                </label>
                            </div>
                            <button id="loginButton" disabled>
                                <div id="loginButtonContent">
                                    LOGIN
                                    <svg id="loginSVG" viewBox="0 0 24.87 13.97">
                                        <defs>
                                            <style>{'.arrowLine{transition: 0.25s ease;}'}</style> {/** TODO */}
                                        </defs>
                                        <polyline className="arrowLine" fill="none" stroke="#FFF" strokeWidth="2px" points="0.71 13.26 12.56 1.41 24.16 13.02"/>
                                    </svg>
                                    <div className="circle-loader">
                                        <div className="checkmark draw"></div>
                                    </div>
                                    {/*<div className="spinningCircle" id="loginSpinner"></div>-*/}
                                </div>
                            </button>
                            <div id="loginDisclaimer">
                                <span className="loginSpanDim" id="loginRegisterSpan">
                                    <a href="https://minecraft.net/en-us/store/minecraft/">Need an Account?</a>
                                </span>
                                <p className="loginDisclaimerText">Your password is sent directly to mojang and never stored.</p>
                                <p className="loginDisclaimerText">Helios Launcher is not affiliated with Mojang AB.</p>
                            </div>
                        </form>
                    </div>
                </div>
            </>
        )
    }

}
